//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_Demo.TopenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopenServiceReference.MsgSendSoap")]
    public interface MsgSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendMes(string userCode, string userPass, string DesNo, string Msg, string Channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBalance(string userCode, string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReport(string userCode, string userPass, string batchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMo(string userCode, string userPass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MsgSendSoapChannel : DotNet_Demo.TopenServiceReference.MsgSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgSendSoapClient : System.ServiceModel.ClientBase<DotNet_Demo.TopenServiceReference.MsgSendSoap>, DotNet_Demo.TopenServiceReference.MsgSendSoap {
        
        public MsgSendSoapClient() {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendMes(string userCode, string userPass, string DesNo, string Msg, string Channel) {
            return base.Channel.sendMes(userCode, userPass, DesNo, Msg, Channel);
        }
        
        public string GetBalance(string userCode, string userPass) {
            return base.Channel.GetBalance(userCode, userPass);
        }
        
        public string GetReport(string userCode, string userPass, string batchNumber) {
            return base.Channel.GetReport(userCode, userPass, batchNumber);
        }
        
        public string GetMo(string userCode, string userPass) {
            return base.Channel.GetMo(userCode, userPass);
        }
    }
}
