#!/bin/bash

# get & analyse params

# display usages in case -?

echo "Usage: "
echo "    startSMSSwitcher [option] [para]"
echo " "
echo "    where <option> is one or all of: "
echo "    -m \t control which module to start "
echo "    sendsms \t to start the send sms function module "
echo "    getrecv \t to start the get reply sms function module "
echo "    getreport \t to start the get report function module "

startModu = 0x0;

if [ $# -eq 0]
	# by default, start all function module except test-module
	startModu = 0x7;
else
	

fi

java -jar SMSSwitch.jar 
